pg_db:
    name: "postgres"
    host: "postgres"
    port: "5432"
    username: "ruslan"

http_server:
    host: "localhost"
    port: "8000"
    timeout: "4s"
    idle_timeout: "60s"
    username: "ruslan"

short_url_pattern: "^[a-zA-Z0-9_]{10}$"